nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["https://frontend-a65.pages.dev"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    expose_headers: ["Content-Type", "Authorization"]
    max_age: 3600
    hosts: []
    origin_regex: false

  paths:
    "^/":
      allow_origin: ["https://frontend-a65.pages.dev"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      expose_headers: ["Content-Type", "Authorization"]
      max_age: 3600
